/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;




import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;



/**
 *
 * @author subsinsriprasert
 */
public final class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
  
    
    
  
    
  
    
  
    
    public Main() {
        initComponents();
        
         ImageIcon myimage=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Board.png")));
        Image img1=myimage.getImage();
        Image img2=img1.getScaledInstance(jLabel25.getWidth(),jLabel25.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon i =new ImageIcon(img2);
        jLabel25.setIcon(i);
       
 
    }
 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel20 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Turn = new javax.swing.JLabel();
        Player1 = new javax.swing.JLabel();
        Moves = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        RollDice = new javax.swing.JButton();
        Dice1 = new javax.swing.JLabel();
        Dice_1 = new javax.swing.JLabel();
        Dice2 = new javax.swing.JLabel();
        Dice_2 = new javax.swing.JLabel();
        Sum = new javax.swing.JLabel();
        Sum_Dices = new javax.swing.JLabel();
        PlayerCard = new javax.swing.JLabel();
        Draw = new javax.swing.JButton();
        Card1 = new javax.swing.JLabel();
        Card2 = new javax.swing.JLabel();
        Card3 = new javax.swing.JLabel();
        EndTurn = new javax.swing.JButton();
        Exit1 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        jLabel20.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel20.setText("Dining");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 51, 0));
        jLabel2.setText("Board Game");

        Turn.setText("Turn");

        Player1.setText("Player1");

        Moves.setText("Moves");

        jLabel6.setText("0");

        RollDice.setText("Roll Dice");
        RollDice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RollDiceActionPerformed(evt);
            }
        });

        Dice1.setText("Dice1");

        Dice_1.setText("0");

        Dice2.setText("Dice2");
        Dice2.setToolTipText("");

        Dice_2.setText("0");

        Sum.setText("Sum");

        Sum_Dices.setText("0");

        PlayerCard.setText("Player Card");

        Draw.setText("Draw");

        Card1.setText("Card 1");

        Card2.setText("Card 2");

        Card3.setText("Card 3");

        EndTurn.setText("End Turn");

        Exit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/icons8-cancel 2.png"))); // NOI18N
        Exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Exit1MousePressed(evt);
            }
        });

        jLabel24.setText("Noted:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(347, 347, 347)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Exit1))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Turn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Player1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Moves)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6))
                    .addComponent(RollDice)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Dice2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Dice_2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Dice1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Dice_1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Sum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Sum_Dices))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(PlayerCard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Draw))
                    .addComponent(Card1)
                    .addComponent(Card2)
                    .addComponent(Card3)
                    .addComponent(EndTurn)
                    .addComponent(jLabel24))
                .addGap(0, 42, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Exit1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Turn)
                            .addComponent(Player1))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Moves)
                            .addComponent(jLabel6))
                        .addGap(20, 20, 20)
                        .addComponent(RollDice)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Dice1)
                            .addComponent(Dice_1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Dice2)
                            .addComponent(Dice_2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Sum)
                            .addComponent(Sum_Dices))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PlayerCard)
                            .addComponent(Draw))
                        .addGap(27, 27, 27)
                        .addComponent(Card1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Card2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Card3)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel24)
                        .addGap(244, 244, 244)
                        .addComponent(EndTurn)))
                .addGap(619, 619, 619))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RollDiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RollDiceActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_RollDiceActionPerformed

    private void Exit1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit1MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_Exit1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Card1;
    private javax.swing.JLabel Card2;
    private javax.swing.JLabel Card3;
    private javax.swing.JLabel Dice1;
    private javax.swing.JLabel Dice2;
    private javax.swing.JLabel Dice_1;
    private javax.swing.JLabel Dice_2;
    private javax.swing.JButton Draw;
    private javax.swing.JButton EndTurn;
    private javax.swing.JLabel Exit1;
    private javax.swing.JLabel Moves;
    private javax.swing.JLabel Player1;
    private javax.swing.JLabel PlayerCard;
    private javax.swing.JButton RollDice;
    private javax.swing.JLabel Sum;
    private javax.swing.JLabel Sum_Dices;
    private javax.swing.JLabel Turn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
