/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;



import java.awt.Image;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;



import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;



/**
 *
 * @author subsinsriprasert
 */
public final class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
         ImageIcon myimage=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Kitchen.jpg")));
        Image img1=myimage.getImage();
        Image img2=img1.getScaledInstance(jLabel1.getWidth(),jLabel1.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon i =new ImageIcon(img2);
        jLabel1.setIcon(i);
       
         ImageIcon icon=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Floor.jpg")));
        Image img=icon.getImage();
        Image img3=img.getScaledInstance(jLabel4.getWidth(),jLabel4.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon x =new ImageIcon(img3);
        jLabel4.setIcon(x);
        
        ImageIcon Garden=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Garden.jpeg")));
        Image img4=Garden.getImage();
        Image img5=img4.getScaledInstance(jLabel3.getWidth(),jLabel3.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon y =new ImageIcon(img5);
        jLabel3.setIcon(y);
        
        ImageIcon Gym=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("gym.jpeg")));
        Image img6=Gym.getImage();
        Image img7=img6.getScaledInstance(jLabel5.getWidth(),jLabel5.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon g =new ImageIcon(img7);
        jLabel5.setIcon(g);
        
        ImageIcon Living=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("livingroom.jpeg")));
        Image img10=Living.getImage();
        Image img11=img10.getScaledInstance(jLabel7.getWidth(),jLabel7.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon l =new ImageIcon(img11);
        jLabel7.setIcon(l);
        
         ImageIcon Dining=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("diningroom.jpeg")));
        Image img8=Dining.getImage();
        Image img9=img8.getScaledInstance(jLabel8.getWidth(),jLabel8.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon D =new ImageIcon(img9);
        jLabel8.setIcon(D);
        
        ImageIcon Bedroom=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Bedroom.jpeg")));
        Image img12=Bedroom.getImage();
        Image img13=img12.getScaledInstance(jLabel9.getWidth(),jLabel9.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon B =new ImageIcon(img13);
        jLabel9.setIcon(B);
       
         ImageIcon office=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("office.jpg")));
        Image img14=office.getImage();
        Image img15=img14.getScaledInstance(jLabel16.getWidth(),jLabel16.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon of =new ImageIcon(img15);
        jLabel16.setIcon(of);
       
        ImageIcon Balcony =new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Balcony.png")));
        Image img16=Balcony.getImage();
        Image img17=img16.getScaledInstance(jLabel17.getWidth(),jLabel17.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon Ba=new ImageIcon(img17);
        jLabel17.setIcon(Ba);
        
        ImageIcon Bathroom =new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Bathroom.png")));
        Image img18=Bathroom.getImage();
        Image img19=img18.getScaledInstance(jLabel18.getWidth(),jLabel18.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon Bath=new ImageIcon(img19);
        jLabel18.setIcon(Bath);
        
         ImageIcon logo =new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
        Image img21=logo.getImage();
        Image img20=img21.getScaledInstance(jLabel23.getWidth(),jLabel23.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon lo=new ImageIcon(img20);
        jLabel23.setIcon(lo);
 
    }
 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel20 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Turn = new javax.swing.JLabel();
        Player1 = new javax.swing.JLabel();
        Moves = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        RollDice = new javax.swing.JButton();
        Dice1 = new javax.swing.JLabel();
        Dice_1 = new javax.swing.JLabel();
        Dice2 = new javax.swing.JLabel();
        Dice_2 = new javax.swing.JLabel();
        Sum = new javax.swing.JLabel();
        Sum_Dices = new javax.swing.JLabel();
        PlayerCard = new javax.swing.JLabel();
        Draw = new javax.swing.JButton();
        Card1 = new javax.swing.JLabel();
        Card2 = new javax.swing.JLabel();
        Card3 = new javax.swing.JLabel();
        EndTurn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Exit1 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        jLabel20.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel20.setText("Dining");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 51, 0));
        jLabel2.setText("Board Game");

        Turn.setText("Turn");

        Player1.setText("Player1");

        Moves.setText("Moves");

        jLabel6.setText("0");

        RollDice.setText("Roll Dice");
        RollDice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RollDiceActionPerformed(evt);
            }
        });

        Dice1.setText("Dice1");

        Dice_1.setText("0");

        Dice2.setText("Dice2");
        Dice2.setToolTipText("");

        Dice_2.setText("0");

        Sum.setText("Sum");

        Sum_Dices.setText("0");

        PlayerCard.setText("Player Card");

        Draw.setText("Draw");

        Card1.setText("Card 1");

        Card2.setText("Card 2");

        Card3.setText("Card 3");

        EndTurn.setText("End Turn");

        jPanel1.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel10.setText("Gym");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(50, 40, 50, 30);

        jLabel23.setText("jLabel23");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(250, 180, 140, 240);

        jLabel21.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel21.setText("Balcony");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(270, 480, 110, 70);

        jLabel22.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel22.setText("BathRoom");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(470, 490, 170, 110);

        jLabel17.setText("jLabel17");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(250, 456, 160, 140);

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel19.setText("Dining");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(520, 382, 120, 40);

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel13.setText("Bedroom");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(520, 50, 90, 22);

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel14.setText("Kitchen");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(523, 220, 90, 20);

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel15.setText("Office");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(70, 480, 120, 40);

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel12.setText("Garden");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(260, 40, 67, 22);

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel11.setText("Library");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(40, 260, 70, 30);

        jLabel1.setText("Kitchen");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(430, 160, 220, 150);

        jLabel3.setText("Garden");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(220, 10, 170, 120);

        jLabel5.setText("Gym");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 180, 160);

        jLabel8.setText("Dining");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(440, 330, 210, 110);

        jLabel7.setText("Library");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 220, 190, 170);

        jLabel9.setText("Bedroom");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(420, 6, 230, 130);

        jLabel16.setText("jLabel16");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(3, 436, 190, 160);
        jPanel1.add(jLabel18);
        jLabel18.setBounds(460, 500, 190, 100);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Floor.jpg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 650, 600);

        Exit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/icons8-cancel 2.png"))); // NOI18N
        Exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Exit1MousePressed(evt);
            }
        });

        jLabel24.setText("Noted:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Turn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Player1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Moves)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6))
                    .addComponent(RollDice)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Dice2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Dice_2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Dice1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Dice_1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Sum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Sum_Dices))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(PlayerCard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Draw))
                    .addComponent(Card1)
                    .addComponent(Card2)
                    .addComponent(Card3)
                    .addComponent(EndTurn)
                    .addComponent(jLabel24))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(347, 347, 347)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Exit1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Exit1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Turn)
                            .addComponent(Player1))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Moves)
                            .addComponent(jLabel6))
                        .addGap(20, 20, 20)
                        .addComponent(RollDice)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Dice1)
                            .addComponent(Dice_1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Dice2)
                            .addComponent(Dice_2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Sum)
                            .addComponent(Sum_Dices))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PlayerCard)
                            .addComponent(Draw))
                        .addGap(27, 27, 27)
                        .addComponent(Card1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Card2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Card3)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EndTurn)))
                .addGap(597, 597, 597))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RollDiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RollDiceActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_RollDiceActionPerformed

    private void Exit1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit1MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_Exit1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Card1;
    private javax.swing.JLabel Card2;
    private javax.swing.JLabel Card3;
    private javax.swing.JLabel Dice1;
    private javax.swing.JLabel Dice2;
    private javax.swing.JLabel Dice_1;
    private javax.swing.JLabel Dice_2;
    private javax.swing.JButton Draw;
    private javax.swing.JButton EndTurn;
    private javax.swing.JLabel Exit1;
    private javax.swing.JLabel Moves;
    private javax.swing.JLabel Player1;
    private javax.swing.JLabel PlayerCard;
    private javax.swing.JButton RollDice;
    private javax.swing.JLabel Sum;
    private javax.swing.JLabel Sum_Dices;
    private javax.swing.JLabel Turn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}



import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;



/**
 *
 * @author subsinsriprasert
 */
public final class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
         ImageIcon myimage=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Kitchen.jpg")));
        Image img1=myimage.getImage();
        Image img2=img1.getScaledInstance(jLabel1.getWidth(),jLabel1.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon i =new ImageIcon(img2);
        jLabel1.setIcon(i);
       
         ImageIcon icon=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Floor.jpg")));
        Image img=icon.getImage();
        Image img3=img.getScaledInstance(jLabel4.getWidth(),jLabel4.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon x =new ImageIcon(img3);
        jLabel4.setIcon(x);
        
        ImageIcon Garden=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Garden.jpeg")));
        Image img4=Garden.getImage();
        Image img5=img4.getScaledInstance(jLabel3.getWidth(),jLabel3.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon y =new ImageIcon(img5);
        jLabel3.setIcon(y);
        
        ImageIcon Gym=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("gym.jpeg")));
        Image img6=Gym.getImage();
        Image img7=img6.getScaledInstance(jLabel5.getWidth(),jLabel5.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon g =new ImageIcon(img7);
        jLabel5.setIcon(g);
        
        ImageIcon Living=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("livingroom.jpeg")));
        Image img10=Living.getImage();
        Image img11=img10.getScaledInstance(jLabel7.getWidth(),jLabel7.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon l =new ImageIcon(img11);
        jLabel7.setIcon(l);
        
         ImageIcon Dining=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("diningroom.jpeg")));
        Image img8=Dining.getImage();
        Image img9=img8.getScaledInstance(jLabel8.getWidth(),jLabel8.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon D =new ImageIcon(img9);
        jLabel8.setIcon(D);
        
        ImageIcon Bedroom=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Bedroom.jpeg")));
        Image img12=Bedroom.getImage();
        Image img13=img12.getScaledInstance(jLabel9.getWidth(),jLabel9.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon B =new ImageIcon(img13);
        jLabel9.setIcon(B);
       
         ImageIcon office=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("office.jpg")));
        Image img14=office.getImage();
        Image img15=img14.getScaledInstance(jLabel16.getWidth(),jLabel16.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon of =new ImageIcon(img15);
        jLabel16.setIcon(of);
       
        ImageIcon Balcony =new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Balcony.png")));
        Image img16=Balcony.getImage();
        Image img17=img16.getScaledInstance(jLabel17.getWidth(),jLabel17.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon Ba=new ImageIcon(img17);
        jLabel17.setIcon(Ba);
        
        ImageIcon Bathroom =new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Bathroom.png")));
        Image img18=Bathroom.getImage();
        Image img19=img18.getScaledInstance(jLabel18.getWidth(),jLabel18.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon Bath=new ImageIcon(img19);
        jLabel18.setIcon(Bath);
        
         ImageIcon logo =new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
        Image img21=logo.getImage();
        Image img20=img21.getScaledInstance(jLabel23.getWidth(),jLabel23.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon lo=new ImageIcon(img20);
        jLabel23.setIcon(lo);
 
    }
 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel20 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Turn = new javax.swing.JLabel();
        Player1 = new javax.swing.JLabel();
        Moves = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        RollDice = new javax.swing.JButton();
        Dice1 = new javax.swing.JLabel();
        Dice_1 = new javax.swing.JLabel();
        Dice2 = new javax.swing.JLabel();
        Dice_2 = new javax.swing.JLabel();
        Sum = new javax.swing.JLabel();
        Sum_Dices = new javax.swing.JLabel();
        PlayerCard = new javax.swing.JLabel();
        Draw = new javax.swing.JButton();
        Card1 = new javax.swing.JLabel();
        Card2 = new javax.swing.JLabel();
        Card3 = new javax.swing.JLabel();
        EndTurn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Exit1 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        jLabel20.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel20.setText("Dining");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 51, 0));
        jLabel2.setText("Board Game");

        Turn.setText("Turn");

        Player1.setText("Player1");

        Moves.setText("Moves");

        jLabel6.setText("0");

        RollDice.setText("Roll Dice");
        RollDice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RollDiceActionPerformed(evt);
            }
        });

        Dice1.setText("Dice1");

        Dice_1.setText("0");

        Dice2.setText("Dice2");
        Dice2.setToolTipText("");

        Dice_2.setText("0");

        Sum.setText("Sum");

        Sum_Dices.setText("0");

        PlayerCard.setText("Player Card");

        Draw.setText("Draw");

        Card1.setText("Card 1");

        Card2.setText("Card 2");

        Card3.setText("Card 3");

        EndTurn.setText("End Turn");

        jPanel1.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel10.setText("Gym");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(50, 40, 50, 30);

        jLabel23.setText("jLabel23");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(250, 180, 140, 240);

        jLabel21.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel21.setText("Balcony");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(270, 480, 110, 70);

        jLabel22.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel22.setText("BathRoom");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(470, 490, 170, 110);

        jLabel17.setText("jLabel17");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(250, 456, 160, 140);

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel19.setText("Dining");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(520, 382, 120, 40);

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel13.setText("Bedroom");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(520, 50, 90, 22);

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel14.setText("Kitchen");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(523, 220, 90, 20);

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel15.setText("Office");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(70, 480, 120, 40);

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel12.setText("Garden");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(260, 40, 67, 22);

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel11.setText("Library");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(40, 260, 70, 30);

        jLabel1.setText("Kitchen");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(430, 160, 220, 150);

        jLabel3.setText("Garden");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(220, 10, 170, 120);

        jLabel5.setText("Gym");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 180, 160);

        jLabel8.setText("Dining");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(440, 330, 210, 110);

        jLabel7.setText("Library");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 220, 190, 170);

        jLabel9.setText("Bedroom");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(420, 6, 230, 130);

        jLabel16.setText("jLabel16");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(3, 436, 190, 160);
        jPanel1.add(jLabel18);
        jLabel18.setBounds(460, 500, 190, 100);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Floor.jpg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 650, 600);

        Exit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/icons8-cancel 2.png"))); // NOI18N
        Exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Exit1MousePressed(evt);
            }
        });

        jLabel24.setText("Noted:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Turn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Player1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Moves)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6))
                    .addComponent(RollDice)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Dice2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Dice_2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Dice1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Dice_1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Sum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Sum_Dices))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(PlayerCard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Draw))
                    .addComponent(Card1)
                    .addComponent(Card2)
                    .addComponent(Card3)
                    .addComponent(EndTurn)
                    .addComponent(jLabel24))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(347, 347, 347)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Exit1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Exit1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Turn)
                            .addComponent(Player1))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Moves)
                            .addComponent(jLabel6))
                        .addGap(20, 20, 20)
                        .addComponent(RollDice)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Dice1)
                            .addComponent(Dice_1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Dice2)
                            .addComponent(Dice_2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Sum)
                            .addComponent(Sum_Dices))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PlayerCard)
                            .addComponent(Draw))
                        .addGap(27, 27, 27)
                        .addComponent(Card1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Card2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Card3)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EndTurn)))
                .addGap(597, 597, 597))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RollDiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RollDiceActionPerformed
        // TODO add your handling code here:
        int dice1 = (int) (Math.random() * 6) + 1;
        int dice2 = (int) (Math.random() * 6) + 1;
        int sum_dice = dice1 + dice2;
        Dice_1.setText(""+dice1);
        Dice_2.setText(""+dice2);
        Sum_Dices.setText(""+sum_dice);
        jLabel6.setText(""+sum_dice);

    }//GEN-LAST:event_RollDiceActionPerformed

    private void Exit1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit1MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_Exit1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Card1;
    private javax.swing.JLabel Card2;
    private javax.swing.JLabel Card3;
    private javax.swing.JLabel Dice1;
    private javax.swing.JLabel Dice2;
    private javax.swing.JLabel Dice_1;
    private javax.swing.JLabel Dice_2;
    private javax.swing.JButton Draw;
    private javax.swing.JButton EndTurn;
    private javax.swing.JLabel Exit1;
    private javax.swing.JLabel Moves;
    private javax.swing.JLabel Player1;
    private javax.swing.JLabel PlayerCard;
    private javax.swing.JButton RollDice;
    private javax.swing.JLabel Sum;
    private javax.swing.JLabel Sum_Dices;
    private javax.swing.JLabel Turn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}

import java.awt.Toolkit;
import javax.swing.ImageIcon;



/**
 *
 * @author subsinsriprasert
 */
public final class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
         ImageIcon myimage=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Kitchen.jpg")));
        Image img1=myimage.getImage();
        Image img2=img1.getScaledInstance(jLabel1.getWidth(),jLabel1.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon i =new ImageIcon(img2);
        jLabel1.setIcon(i);
       
         ImageIcon icon=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Floor.jpg")));
        Image img=icon.getImage();
        Image img3=img.getScaledInstance(jLabel4.getWidth(),jLabel4.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon x =new ImageIcon(img3);
        jLabel4.setIcon(x);
        
        ImageIcon Garden=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Garden.jpeg")));
        Image img4=Garden.getImage();
        Image img5=img4.getScaledInstance(jLabel3.getWidth(),jLabel3.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon y =new ImageIcon(img5);
        jLabel3.setIcon(y);
        
        ImageIcon Gym=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("gym.jpeg")));
        Image img6=Gym.getImage();
        Image img7=img6.getScaledInstance(jLabel5.getWidth(),jLabel5.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon g =new ImageIcon(img7);
        jLabel5.setIcon(g);
        
        ImageIcon Living=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("livingroom.jpeg")));
        Image img10=Living.getImage();
        Image img11=img10.getScaledInstance(jLabel7.getWidth(),jLabel7.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon l =new ImageIcon(img11);
        jLabel7.setIcon(l);
        
         ImageIcon Dining=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("diningroom.jpeg")));
        Image img8=Dining.getImage();
        Image img9=img8.getScaledInstance(jLabel8.getWidth(),jLabel8.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon D =new ImageIcon(img9);
        jLabel8.setIcon(D);
        
        ImageIcon Bedroom=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Bedroom.jpeg")));
        Image img12=Bedroom.getImage();
        Image img13=img12.getScaledInstance(jLabel9.getWidth(),jLabel9.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon B =new ImageIcon(img13);
        jLabel9.setIcon(B);
       
        
 
    }
 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Turn = new javax.swing.JLabel();
        Player1 = new javax.swing.JLabel();
        Moves = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        RollDice = new javax.swing.JButton();
        Dice1 = new javax.swing.JLabel();
        Dice_1 = new javax.swing.JLabel();
        Dice2 = new javax.swing.JLabel();
        Dice_2 = new javax.swing.JLabel();
        Sum = new javax.swing.JLabel();
        Sum_Dices = new javax.swing.JLabel();
        PlayerCard = new javax.swing.JLabel();
        Draw = new javax.swing.JButton();
        Card1 = new javax.swing.JLabel();
        Card2 = new javax.swing.JLabel();
        Card3 = new javax.swing.JLabel();
        EndTurn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Exit1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 51, 0));
        jLabel2.setText("Board Game");

        Turn.setText("Turn");

        Player1.setText("Player1");

        Moves.setText("Moves");

        jLabel6.setText("0");

        RollDice.setText("Roll Dice");
        RollDice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RollDiceActionPerformed(evt);
            }
        });

        Dice1.setText("Dice1");

        Dice_1.setText("0");

        Dice2.setText("Dice2");
        Dice2.setToolTipText("");

        Dice_2.setText("0");

        Sum.setText("Sum");

        Sum_Dices.setText("0");

        PlayerCard.setText("Player Card");

        Draw.setText("Draw");

        Card1.setText("Card 1");

        Card2.setText("Card 2");

        Card3.setText("Card 3");

        EndTurn.setText("End Turn");

        jPanel1.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel10.setText("Gym");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(50, 40, 50, 30);

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel13.setText("Bedroom");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(520, 50, 90, 22);

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel14.setText("Kitchen");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(523, 220, 90, 20);

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel15.setText("Dining");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(520, 382, 120, 40);

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel12.setText("Garden");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(260, 40, 67, 22);

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel11.setText("Library");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(40, 260, 70, 30);

        jLabel1.setText("Kitchen");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(430, 160, 220, 150);

        jLabel3.setText("Garden");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(220, 10, 170, 120);

        jLabel5.setText("Gym");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 180, 160);

        jLabel8.setText("Dining");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(440, 340, 210, 130);

        jLabel7.setText("Library");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 220, 190, 140);

        jLabel9.setText("Bedroom");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(420, 6, 230, 130);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Floor.jpg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 650, 600);

        Exit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/icons8-cancel 2.png"))); // NOI18N
        Exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Exit1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Turn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Player1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Moves)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6))
                            .addComponent(RollDice)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Dice2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dice_2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Dice1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Dice_1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Sum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Sum_Dices))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(PlayerCard)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Draw))
                            .addComponent(Card1)
                            .addComponent(Card2)
                            .addComponent(Card3)
                            .addComponent(EndTurn))))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(878, Short.MAX_VALUE)
                    .addComponent(Exit1)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Turn)
                            .addComponent(Player1))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Moves)
                            .addComponent(jLabel6))
                        .addGap(20, 20, 20)
                        .addComponent(RollDice)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Dice1)
                            .addComponent(Dice_1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Dice2)
                            .addComponent(Dice_2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Sum)
                            .addComponent(Sum_Dices))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PlayerCard)
                            .addComponent(Draw))
                        .addGap(27, 27, 27)
                        .addComponent(Card1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Card2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Card3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EndTurn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(597, 597, 597))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Exit1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1206, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RollDiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RollDiceActionPerformed
        // TODO add your handling code here:
        int dice1 = (int) (Math.random() * 6) + 1;
        int dice2 = (int) (Math.random() * 6) + 1;
        int sum_dice = dice1 + dice2;
        Dice_1.setText(""+dice1);
        Dice_2.setText(""+dice2);
        Sum_Dices.setText(""+sum_dice);
        jLabel6.setText(""+sum_dice);

    }//GEN-LAST:event_RollDiceActionPerformed

    private void Exit1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit1MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_Exit1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Card1;
    private javax.swing.JLabel Card2;
    private javax.swing.JLabel Card3;
    private javax.swing.JLabel Dice1;
    private javax.swing.JLabel Dice2;
    private javax.swing.JLabel Dice_1;
    private javax.swing.JLabel Dice_2;
    private javax.swing.JButton Draw;
    private javax.swing.JButton EndTurn;
    private javax.swing.JLabel Exit1;
    private javax.swing.JLabel Moves;
    private javax.swing.JLabel Player1;
    private javax.swing.JLabel PlayerCard;
    private javax.swing.JButton RollDice;
    private javax.swing.JLabel Sum;
    private javax.swing.JLabel Sum_Dices;
    private javax.swing.JLabel Turn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
